RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"
baseURL = "https://serverless-observability.workshop.aws/"



title = "AWS Serverless Observability Workshop"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = false
sectionPagesMenu = "main"

enableEmoji = true

[params]
editURL = "https://github.com/aws-samples/serverless-observability-workshop/edit/master/workshop/content/"
description = "AWS Serverless Observability Workshop"
author = "Enrico Bergamo"
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "mine"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = false
disableShortcutsTitle = false
disableInlineCopyToClipBoard = true
#pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[outputs]
home = [ "HTML", "RSS", "JSON"]
page = [ "HTML" ]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[Languages]
[Languages.en]
title = "AWS Serverless Observability Workshop"
weight = 1
languageName = "English"

  [[Languages.en.menu.shortcuts]]
  name = "<i class='fas fa-tags'></i> Tags"
  url = "tags.html"
  weight = 1
  
  [[Languages.en.menu.shortcuts]]
  name = "<i class='fas fa-bookmark'></i> More Resources"
  url = "more_resources.html"
  weight = 2

  [[Languages.en.menu.shortcuts]]
  name = "<i class='fas fa-users'></i> Authors"
  url = "authors.html"
  weight = 3

  [[Languages.en.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> GitHub Project"
  url = "https://github.com/aws-samples/serverless-observability-workshop"
  weight = 4

  [[Languages.en.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> Feedback / Questions?"
  url = "mailto:serverless-observability-workshop@amazon.com"
  weight = 5

[Languages.es]
title = "AWS Serverless Observability Workshop"
weight = 2
languageName = "Español"

  [[Languages.es.menu.shortcuts]]
  name = "<i class='fas fa-tags'></i> Tags"
  url = "tags.html"
  weight = 1
  
  [[Languages.es.menu.shortcuts]]
  name = "<i class='fas fa-bookmark'></i> Más Recursos"
  url = "more_resources.html"
  weight = 2

  [[Languages.es.menu.shortcuts]]
  name = "<i class='fas fa-users'></i> Autores"
  url = "authors.html"
  weight = 3

  [[Languages.es.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Proyecto en GitHub"
  url = "https://github.com/aws-samples/serverless-observability-workshop"
  weight = 4

  [[Languages.es.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> Feedback / Preguntas?"
  url = "mailto:serverless-observability-workshop@amazon.com"
  weight = 5

[Languages.pt]
title = "AWS Serverless Observability Workshop"
weight = 3
languageName = "Português"

  [[Languages.pt.menu.shortcuts]]
  name = "<i class='fas fa-tags'></i> Tags"
  url = "tags.html"
  weight = 1
  
  [[Languages.pt.menu.shortcuts]]
  name = "<i class='fas fa-bookmark'></i> Mais Recursos"
  url = "more_resources.html"
  weight = 2

  [[Languages.pt.menu.shortcuts]]
  name = "<i class='fas fa-users'></i> Autores"
  url = "authors.html"
  weight = 3

  [[Languages.pt.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Projeto no GitHub"
  url = "https://github.com/aws-samples/serverless-observability-workshop"
  weight = 4

  [[Languages.pt.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> Feedback / Perguntas?"
  url = "mailto:serverless-observability-workshop@amazon.com"
  weight = 5
